### ISSUE TITLE
biggest rat ever

### ISSUE THREAD

**Issue by 1x4z** [Hermivore8151/Bindable-LagSwitch#1]
i stopped using this after i realized i got 7 trojans

**Comment by LoneTravler** [comment]
Windows defender came in clutch here

**Comment by Hermivore8151** [comment]
The switch isn't a Trojan, it's in python and you can reverse engineer it very easily, it's made using auto py to exe, and I use it myself

chances are, you got a Trojan from somewhere else, as for windows defender,
it's probably because it's an unmarked program
