### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Smilez1010** [Hermivore8151/Bindable-LagSwitch#3]
Did a scan and found viruses (Do not download). You can check for viruses or any application you might find like this and do a scan on Triage

**Comment by Hermivore8151** [comment]
![image](https://github.com/user-attachments/assets/8460644c-b7d3-4181-974a-eed639875fe5)
lol.
look whos the one with a virus here

**Comment by Hermivore8151** [comment]
your unedited comment contained a link containing a virus, the .exe is the one i use for myself lol
grabify link.. lol.
